# Generated by Django 4.2.1 on 2023-05-14 20:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('model_name', models.CharField(max_length=32)),
                ('text_data', models.TextField()),
                ('file_data', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='data_path',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_status',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 14, 20, 37, 44, 897892, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='data_dir',
            field=models.CharField(default='example_dir', max_length=512),
        ),
        migrations.AddField(
            model_name='job',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 14, 20, 37, 44, 897892, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reference',
            field=models.CharField(default=uuid.UUID('3f1f1e36-5b4b-4ba1-9b83-de11156f263b'), max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='example_status', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.CharField(default='example@example.com', max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='model_name',
            field=models.CharField(default='example_model', max_length=32),
        ),
    ]
