# Generated by Django 4.2.1 on 2023-05-15 08:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jobrequest_remove_job_data_path_remove_job_job_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(max_length=256)),
                ('email', models.TextField(max_length=256)),
                ('model_name', models.TextField(max_length=32)),
                ('status', models.TextField(max_length=16)),
                ('link', models.TextField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 15, 8, 2, 26, 976636, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='data_dir',
            field=models.TextField(default='example_dir', max_length=512),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.TextField(default='example@example.com', max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='model_name',
            field=models.TextField(default='example_model', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 15, 8, 2, 26, 976636, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='reference',
            field=models.TextField(default=uuid.UUID('df3a96b3-5cca-46e4-9605-f9055eee305a'), max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.TextField(default='example_status', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='email',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='model_name',
            field=models.TextField(max_length=32),
        ),
    ]
