# Generated by Django 4.2.1 on 2023-05-23 01:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_jobresponse_alter_job_created_at_alter_job_data_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 1, 2, 20, 937776, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 1, 2, 20, 937776, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='reference',
            field=models.TextField(default=uuid.UUID('550a3d15-1a59-4113-9cd5-50127ff13397'), max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=256),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='file_data',
            field=models.FileField(blank=True, default='./jobs/default/default.txt', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='model_name',
            field=models.TextField(default='example_model', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='text_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='jobresponse',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
