FROM httpd:2.4

COPY ./*.html /usr/local/apache2/htdocs/
COPY ./assets/*  /usr/local/apache2/htdocs/assets/
COPY ./css/* /usr/local/apache2/htdocs/css/
COPY ./js/* /usr/local/apache2/htdocs/js/

EXPOSE 80