# Generated by Django 4.0.4 on 2023-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAcceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/data/HMSVWAEDZWTO')),
            ],
        ),
    ]
