# Generated by Django 4.0.4 on 2023-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNNSPliceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoracceptor',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/data/JFGTZINOWNLK'),
        ),
    ]
