# Generated by Django 4.0.4 on 2023-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNNSPliceAPI', '0002_alter_donoracceptor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoracceptor',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/data/VZTYHZIHHRBU'),
        ),
    ]
