# Generated by Django 4.2 on 2023-05-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CNNSPliceAPI", "0003_alter_donoracceptor_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="donoracceptor",
            name="speciesChoice",
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="donoracceptor",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="static/data/EBORDIGNXJEM",
            ),
        ),
    ]
