# Generated by Django 4.2 on 2023-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CNNSPliceAPI", "0004_donoracceptor_specieschoice_alter_donoracceptor_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donoracceptor",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="donoracceptor",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="static/data/TTUTCKXEFTMU",
            ),
        ),
    ]
