# Generated by Django 4.2 on 2023-05-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CNNSPliceAPI", "0008_alter_donoracceptor_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="donoracceptor", name="file",),
    ]
