# Generated by Django 4.2 on 2023-05-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CNNSPliceAPI", "0009_remove_donoracceptor_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="donoracceptor",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="static/data/HRTABQUQEBHK",
            ),
        ),
    ]
